name: Update River Level

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pandas requests lxml

      - run: python main.py

      - run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add cache/prefectura_latest.json
          git commit -m "update river" || echo "no changes"
          git push